version: "3.8"

services:
    # Django Service
    django:
        env_file: .env
        build: .
        container_name: django
        command: >
            bash -c "python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
            - postgres

    # Celery Service
    celery:
        env_file: .env

        build: .
        command: >
            bash -c "sleep 5 &&
                     celery -A django_happy_birthday worker -l INFO"
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
            - postgres

    # PostgreSQL Database Service
    postgres:
        image: 'postgres:15.5'
        env_file: .env
        ports:
            - ${POSTGRES_PORT}:5432
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
            interval: 1s
            timeout: 1s
            retries: 60
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # Redis Service
    redis:
        image: "redis:alpine"
